---
- name: Modify security group for win ec2 instance(s) https / nessus agent
  ec2_group:
    aws_access_key: '{{aws_access_key|default(omit)}}'
    aws_secret_key: '{{aws_secret_key|default(omit)}}'
    region: '{{win_ec2_region|mandatory}}'
    name: '{{win_ec2_security_group}}'
    description: '{{win_ec2_security_group_description|default("")}}'
    vpc_id: '{{win_ec2_vpc_id|default(omit)}}'
    state: present
    rules: "{{win_ec2_security_group_rules|list}}"
  when: 'win_ec2_security_group|default("",true) and win_ec2_images and "create" in win_ec2_action'
  register: win_ec2_security_group_result
