---
- name:  Basic SQL Server Playbook
  hosts: Windows
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore

  tasks:
    - name: Run command that only runs if folder exists and runs from a specific folder
      win_command: wbadmin -backupTarget:C:\backup\
      args:
        chdir: C:\somedir\
        creates: C:\backup\    