---
- name:  Basic Playbook to shutdown IIS server
  hosts: all
  
  tasks:
    - name: stop the iis service for failover test
      win_service:
        name: W3Svc
        state: stopped

    - debug: var=hostvars[inventory_hostname]['ansible_enp0s3']['ipv4']['address']
