---
- name:  Basic Playbook to shutdown IIS server
  hosts: all
  gather_facts: yes
  
  tasks:
    - name: stop the iis service for failover test
      win_service:
        name: W3Svc
        state: stopped

    - name: Display IP addrress of IIS Server
      debug:
        msg:
          - "{{ ansible_hostname }}" 
  