---
- name:  Basic Notification
  hosts: all

  tasks:
    - name: win ping test
      win_ping: 

    - name: Placeholder for real notification
      debug:
        msg:
          - "Notify service management"
        