---
- name:  Basic IIS Website Test
  hosts: all

  tasks:
    - name: Check that you can connect (GET) to a page and it returns a status 200
      uri:
        url: http://{{ results_web_server_ip }}/
        return_content: true
      register: result


    - name: "Copy the result into a varible to be used by next part of workflow"
      set_stats:
        data:
          results_url:  "{{ result }}" 
        