---
- name:  Basic Playbook to that runs Test-Connect
  hosts: all
  gather_facts: yes

  tasks:

  - name: Checking Connectivity to Symantec Server (192.168.11.10) on port 32768
    win_shell:  Test-NetConnection -ComputerName 192.168.11.10 -Port 32768
    register: result


  - debug:
        var: results.stdout_lines