---
- name:  Basic Windows Playbook
  hosts: Windows
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: win ping test
      win_ping: 
        