---
- name : "Manage EC2 Instance"
  hosts: localhost 
  gather_facts: False
  tasks: 
  - name: Enumerate all tagged instances in ec2
    ec2_instance_facts:
      filters:
        "tag:Name={{ instance_tag }}"
      region: "{{ ec2_region }}"
    register: vmfacts 


  - debug: msg="{{ item.instance_id }}"
    with_items: "{{ vmfacts.instances }}"


  - name: Set ami instance in ec2 to "{{ action }}"
    ec2:
      region: 'ap-southeast-2'
      state: "{{ action }}"
      instance_ids: '{{ item.instance_id }}'
    with_items: '{{ vmfacts.instances }}'
